brain_seg_ui/segmentation/auth.py
from flask import (
    Blueprint, 
    render_template, 
    flash,
    request, 
    redirect,  
    url_for
)
from .forms import SignupForm, LoginForm
from .enums import Roles
from flask_login import (
    current_user,
    login_user
)

from .models import db, User
from . import login_manager

from .utils import util_create_user

auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.home'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(medical_id = form.medical_id.data).first()
        # if user.role != Roles.neurologist.value or user.role != Roles.sonographer.value:
        #     return redirect(url_for('auth_bp.login'))
                
        if user and user.check_password(password = form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for('main_bp.upload_scans'))
        
        flash('Invalid medical ID or password.')
        return redirect(url_for('auth_bp.login'))
    
    return render_template(
        'login.html',
        form = form,
        title = 'Log In.',
        template = 'login-page',
    )

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(medical_id = form.medical_id.data).first()
        
        if existing_user is None:
            user = util_create_user(form)
            if user:
                print('User: ', user.medical_id)
                login_user(user)
                return redirect(url_for('main_bp.home'))
    
    return render_template(
        'signup.html',
        title = 'Create an Account',
        form = form,
        template = 'signup-page',
    )
    
    
@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("You must be logged in to view that page.")
    return redirect(url_for("auth_bp.login"))
    
    
    

brain_seg_ui/segmentation/routes.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required, logout_user
from .enums import Roles
from .forms import UploadScansForm
from .models import db, User
from .utils import *

# Blueprint Configuration
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)


@main_bp.route("/", methods=["GET"])
@login_required
def home():
    return render_template(
        "home.html",
        title="Home - Brain Tumor Segmentation",
        template="home-template",
        current_user=current_user,
        neur = Roles.neurologist,
    )
    
    
@main_bp.route('/seed_patients', methods=['GET'])
@login_required
def seed_patients():
    util_seed_patients()
    return redirect(url_for('main_bp.home'))

    

@main_bp.route('/upload_scans', methods=['GET', 'POST'])
@login_required
def upload_scans():
    form = UploadScansForm()
    
    if form.validate_on_submit():
        success = util_upload_and_segment(form)               
        
        if success:           
            return redirect(url_for('main_bp.upload_scans'))
    
    return render_template(
        "upload_scans.html",
        title="Upload Scans",
        form = form,
        template = 'signup-page',
        neur = Roles.neurologist,
    )

@main_bp.route('/view_patients', methods=['GET'])
@login_required
def view_patients():
    patients = db.session.query(User).filter(User.role == None)
        
    return render_template(
        'patients.html',
        template = 'dashboard-page',
        patients = patients,
        body = 'View Patients',
        neur = Roles.neurologist,

    )

@main_bp.route('/view_scans/<patient_ID>', methods=['GET'])
@login_required
def view_scans(patient_ID):
    response = util_get_scans(patient_ID)
    
    if response['status'] == 200: 
        scans_list = response['scans']
        patient = response['patient']           
        return render_template('scans.html',
                            scans = scans_list,
                            template = 'dashboard-page',
                            body = 'Scans for: ' + ' ' +  str(patient.medical_id) + ' - ' + patient.first_name + ' ' + patient.last_name,
                            neur = Roles.neurologist,
                            )
    return redirect('main_bp.view_patients')

@main_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth_bp.login"))

brain_seg_ui/segmentation/templates/home.html
{% extends "layout.html" %} {% block pagestyles %}
<link
  href="{{ url_for('static', filename='dist/css/dashboard.css') }}"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css" />
{% endblock %} {% block content %}
<h1>{{ body }}</h1>

{% if current_user.is_authenticated %}
<p>Hi {{ current_user.first_name }}!</p>
{% endif %} {% endblock %}

brain_seg_ui/segmentation/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{ title }}</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, viewport-fit=cover"
    />
    <meta name="theme-color" content="#5eb9d7" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='dist/img/favicon.png') }}"
      type="image/x-icon"
    />
    <meta
      property="og:description"
      content="Add user authentication to your Flask app."
    />
    <meta name="twitter:title" content="{{ title }}" />
    <link
      href="https://fonts.googleapis.com/css?family=Poppins:200,300,500"
      rel="stylesheet"
    />
    {% block pagestyles %}{% endblock %}
  </head>

  <body class="{{ template }}">
    <div class="container">
      {% include 'nav.html' %} {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('main_bp.static', filename='dist/js/main.min.js') }}"></script>
    {% block additionalscripts %}{% endblock %}
  </body>
</html>

brain_seg_ui/segmentation/templates/login.html
{% extends 'layout.html' %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class = 'form-wrapper'>
        <div class = 'logo'>
            <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>        </div>
        {% for message in get_flasked_messages %}
            <div class = 'alert alert-warning'>
                <button type = 'button' class = 'close' data-dismiss = 'alert'>
                    x
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <h1>Log In</h1>

        <form method = 'POST' action = '/login'>
            {{ form.csrf_token }}

            <fieldset class = 'medical_id'>
                {{ form.medical_id.label }}    
                {{ form.medical_id(placeholder = '1234567') }}
                {% if form.medical_id.errors %}
                    <ul class = 'errors'>
                        {% for error in form.medical_id.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'password'>
                {{ form.password.label }} 
                {{ form.password }}   
                {% if form.password.errors %}
                    <ul class = 'errors'>
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <div class = 'submit-button'>
                {{ form.submit }}
            </div>
        </form>

        <div class = 'login-signup'>
            <div>
                <span>Don't have an account?</span>
                <a href = {{ url_for('auth_bp.signup') }}>Sign Up.</a>
            </div>
        </div>
    </div>
{% endblock %}   

brain_seg_ui/segmentation/templates/nav.html
{% if current_user.is_authenticated %}
<header>
  <nav>
    <span id="left">
      <img
        style="
          width: 5%;
          height: 5%;
          margin-right: 40px;
          margin-left: -20px;
          margin-bottom: -20px;
        "
        src="{{ url_for('static', filename='dist/img/logo.png') }}"
        alt="logo"
      />
      <a href="{{ url_for('main_bp.upload_scans') }}">Upload Scans</a>
      {% if current_user.role == neur %}
      <a href="{{ url_for('main_bp.view_patients') }}">View Patient Results</a>
      {% endif %}
    </span>
    <span id="right">
      <a href="">{{ current_user.first_name + ' ' + current_user.last_name}}</a>
      <a href="{{ url_for('main_bp.logout') }}">Log out</a>
    </span>
  </nav>
</header>
{% endif %}

brain_seg_ui/segmentation/templates/patients.html
{% extends "layout.html" %} {% block pagestyles %}
<link
  href="{{ url_for('static', filename='dist/css/dashboard.css') }}"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css" />
{% endblock %} {% block content %}
<h1>{{ body }}</h1>

<table class="styled-table">
  <thead>
    <tr>
      <th>Patient ID</th>
      <th>Patient Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for patient in patients %}
    <tr>
      <td>{{ patient.medical_id }}</td>
      <td>{{ patient.first_name + ' ' + patient.last_name }}</td>
      <td>
        {% if patient.scans %}
        <a
          href="{{ url_for('main_bp.view_scans', patient_ID=patient.id) }}"
          style="
            text-decoration: none;
            background-color: #344372;
            color: #fff;
            padding: 8px 10px;
            border-radius: 6%;
          "
          >View Scans</a
        >
        {% else %} No scans segmented yet {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

brain_seg_ui/segmentation/templates/scans.html
{% extends "layout.html" %} {% block pagestyles %}
<link
  href="{{ url_for('static', filename='dist/css/dashboard.css') }}"
  rel="stylesheet"
  type="text/css"
/>
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css" />
{% endblock %} {% block content %}

<h1>{{ body }}</h1>

<div class="clearfix">
  <h4>Tumor Regions:</h4>
  <div style="margin-left: 30px" class="key blue">=> Necrotic tumor</div>
  <div class="key yellow">=> Edema (invaded tissue)</div>
  <div class="key green">=> Enhancing tumor</div>
</div>

<div class="clearfix">
  {% for scan in scans %}
  <h2>For {{ scan.created_on }}:</h2>
  <div class="img-container">
    <img
      src="{{ url_for('static', filename=scan.scan) }}"
      alt="Italy"
      style="width: 100%"
    />
  </div>
  <div class="img-container">
    <img
      src="{{ url_for('static', filename=scan.predicted) }}"
      alt="Forest"
      style="width: 100%"
    />
  </div>
  {% endfor %}
</div>

{% endblock %}

brain_seg_ui/segmentation/templates/signup.html
{% extends 'layout.html' %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class = 'form-wrapper'>
        <div class = 'logo'>
            <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
        </div>
        {% for message in get_flasked_messages %}
            <div class = 'alert alert-warning'>
                <button type = 'button' class = 'close' data-dismiss = 'alert'>
                    x
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <h1>Sign Up</h1>

        <form method = 'POST' action = '/signup'>
            {{ form.csrf_token }}

            <fieldset class = 'medical_id'>
                {{ form.medical_id.label }}    
                {{ form.medical_id(placeholder = '1234567') }}
                {% if form.medical_id.errors %}
                    <ul class = 'errors'>
                        {% for error in form.medical_id.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'first_name'>
                {{ form.first_name.label }}    
                {{ form.first_name(placeholder = 'John') }}
                {% if form.first_name.errors %}
                    <ul class = 'errors'>
                        {% for error in form.first_name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'last_name'>
                {{ form.last_name.label }}    
                {{ form.last_name(placeholder = 'Smith') }}
                {% if form.last_name.errors %}
                    <ul class = 'errors'>
                        {% for error in form.last_name.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'phone_no'>
                {{ form.phone_no.label }}    
                {{ form.phone_no(placeholder = '0712345678') }}
                {% if form.phone_no.errors %}
                    <ul class = 'errors'>
                        {% for error in form.phone_no.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'email'>
                {{ form.email.label }}    
                {{ form.email(placeholder = 'youremail@example.com') }}
                {% if form.email.errors %}
                    <ul class = 'errors'>
                        {% for error in form.email.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'role'>
                {{ form.role.label }}    
                {{ form.role }}    
                {% if form.role.errors %}
                    <ul class = 'errors'>
                        {% for error in form.role.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'password'>
                {{ form.password.label }}  
                {{ form.password }}     
                {% if form.password.errors %}
                    <ul class = 'errors'>
                        {% for error in form.password.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'confirm'>
                {{ form.confirm.label }}  
                {{ form.confirm }}
                {% if form.confirm.errors %}
                    <ul class = 'errors'>
                        {% for error in form.confirm.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <div class = 'submit-button'>
                {{ form.submit }}
            </div>
        </form>

        <div class = 'login-signup'>
            <div>
                <span>Already have an account?</span>
                <a href = {{ url_for('auth_bp.login') }}>Log in.</a>
            </div>
        </div>
    </div>
{% endblock %}

brain_seg_ui/segmentation/templates/upload_scans.html
{% extends 'layout.html' %}

{% block pagestyles %}
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css" />
  <link href="{{ url_for('static', filename='dist/css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class = 'form-wrapper' style="margin-top: 40px; width: 600px;">
        <div class = 'logo'>
            <img src="{{ url_for('static', filename='dist/img/logo.png') }}" alt="logo"/>
        </div>
        {% for message in get_flasked_messages %}
            <div class = 'alert alert-warning'>
                <button type = 'button' class = 'close' data-dismiss = 'alert'>
                    x
                </button>
                {{ message }}
            </div>
        {% endfor %}

        <h1>Upload Scans</h1>

        <form method = 'POST' action = '/upload_scans' enctype="multipart/form-data">
            {{ form.csrf_token }}

            <fieldset class = 'patient'>
                {{ form.patient.label }}    
                {{ form.patient }}
                {% if form.patient.errors %}
                    <ul class = 'errors'>
                        {% for error in form.patient.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 'flair_scan'>
                {{ form.flair_scan.label }}    
                {{ form.flair_scan(placeholder = 'FLAIR Scan') }}
                {% if form.flair_scan.errors %}
                    <ul class = 'errors'>
                        {% for error in form.flair_scan.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 't1ce_scan'>
                {{ form.t1ce_scan.label }}    
                {{ form.t1ce_scan(placeholder = 'T1CE Scan') }}
                {% if form.t1ce_scan.errors %}
                    <ul class = 'errors'>
                        {% for error in form.t1ce_scan.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <fieldset class = 't2_scan'>
                {{ form.t2_scan.label }}    
                {{ form.t2_scan(placeholder = 'T2 Scan') }}
                {% if form.t2_scan.errors %}
                    <ul class = 'errors'>
                        {% for error in form.t2_scan.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            <fieldset>

            <div class = 'submit-button'>
                {{ form.submit }}
            </div>
        </form>
    </div>
{% endblock %}